--Create Overview Dashboard
insert into "METRIC2"."M2_DASHBOARD" values("METRIC2"."DASHBOARD_ID".NEXTVAL,'Memory',null,null,1,null,null,null,null,null);

-- Create Widgets on Overview Dashboard
insert into "METRIC2"."M2_DASHBOARD_WIDGET" values("METRIC2"."DASHBOARD_WIDGET_ID".NEXTVAL,"METRIC2"."DASHBOARD_ID".CURRVAL,13,'Memory Used',1,1,2,3,0);
insert into "METRIC2"."M2_DASHBOARD_WIDGET_PARAMS" values("METRIC2"."DASHBOARD_WIDGET_PARAM_ID".NEXTVAL,"METRIC2"."DASHBOARD_WIDGET_ID".CURRVAL,54,'SELECT RND FROM METRIC2.M2_WIDGET_FREEPHYSMEM',13,CURRENT_TIMESTAMP);
insert into "METRIC2"."M2_DASHBOARD_WIDGET_PARAMS" values("METRIC2"."DASHBOARD_WIDGET_PARAM_ID".NEXTVAL,"METRIC2"."DASHBOARD_WIDGET_ID".CURRVAL,45,'localserver',13,CURRENT_TIMESTAMP);
insert into "METRIC2"."M2_DASHBOARD_WIDGET_PARAMS" values("METRIC2"."DASHBOARD_WIDGET_PARAM_ID".NEXTVAL,"METRIC2"."DASHBOARD_WIDGET_ID".CURRVAL,56,'SELECT * FROM METRIC2.M2_WIDGET_PHYSICALMEM',13,CURRENT_TIMESTAMP);


insert into "METRIC2"."M2_DASHBOARD_WIDGET" values("METRIC2"."DASHBOARD_WIDGET_ID".NEXTVAL,"METRIC2"."DASHBOARD_ID".CURRVAL,14,'Res. Mem. Used History',1,1,1,5,0);
insert into "METRIC2"."M2_DASHBOARD_WIDGET_PARAMS" values("METRIC2"."DASHBOARD_WIDGET_PARAM_ID".NEXTVAL,"METRIC2"."DASHBOARD_WIDGET_ID".CURRVAL,59,'20',14,CURRENT_TIMESTAMP);
insert into "METRIC2"."M2_DASHBOARD_WIDGET_PARAMS" values("METRIC2"."DASHBOARD_WIDGET_PARAM_ID".NEXTVAL,"METRIC2"."DASHBOARD_WIDGET_ID".CURRVAL,58,'SELECT * FROM METRIC2.M2_WIDGET_PHYSICALMEM',14,CURRENT_TIMESTAMP);
insert into "METRIC2"."M2_DASHBOARD_WIDGET_PARAMS" values("METRIC2"."DASHBOARD_WIDGET_PARAM_ID".NEXTVAL,"METRIC2"."DASHBOARD_WIDGET_ID".CURRVAL,57,'localserver',14,CURRENT_TIMESTAMP);
insert into "METRIC2"."M2_DASHBOARD_WIDGET_PARAMS" values("METRIC2"."DASHBOARD_WIDGET_PARAM_ID".NEXTVAL,"METRIC2"."DASHBOARD_WIDGET_ID".CURRVAL,60,'line',14,CURRENT_TIMESTAMP);


insert into "METRIC2"."M2_DASHBOARD_WIDGET" values("METRIC2"."DASHBOARD_WIDGET_ID".NEXTVAL,"METRIC2"."DASHBOARD_ID".CURRVAL,21,'System Overview',4,1,1,1,0);
insert into "METRIC2"."M2_DASHBOARD_WIDGET_PARAMS" values("METRIC2"."DASHBOARD_WIDGET_PARAM_ID".NEXTVAL,"METRIC2"."DASHBOARD_WIDGET_ID".CURRVAL,75,'localserver',21,CURRENT_TIMESTAMP);
insert into "METRIC2"."M2_DASHBOARD_WIDGET_PARAMS" values("METRIC2"."DASHBOARD_WIDGET_PARAM_ID".NEXTVAL,"METRIC2"."DASHBOARD_WIDGET_ID".CURRVAL,76,'SELECT SM FROM METRIC2.M2_WIDGET_TOTAL_CPU',21,CURRENT_TIMESTAMP);
insert into "METRIC2"."M2_DASHBOARD_WIDGET_PARAMS" values("METRIC2"."DASHBOARD_WIDGET_PARAM_ID".NEXTVAL,"METRIC2"."DASHBOARD_WIDGET_ID".CURRVAL,77,'SELECT SM FROM METRIC2.M2_WIDGET_SYS_MEM',21,CURRENT_TIMESTAMP);
insert into "METRIC2"."M2_DASHBOARD_WIDGET_PARAMS" values("METRIC2"."DASHBOARD_WIDGET_PARAM_ID".NEXTVAL,"METRIC2"."DASHBOARD_WIDGET_ID".CURRVAL,79,'SELECT VALUE FROM METRIC2.M2_WIDGET_ALLSTARTED_VALUE',21,CURRENT_TIMESTAMP);
insert into "METRIC2"."M2_DASHBOARD_WIDGET_PARAMS" values("METRIC2"."DASHBOARD_WIDGET_PARAM_ID".NEXTVAL,"METRIC2"."DASHBOARD_WIDGET_ID".CURRVAL,80,'SELECT VALUE FROM METRIC2.M2_WIDGET_DISTRIBUTED_VALUE',21,CURRENT_TIMESTAMP);


insert into "METRIC2"."M2_DASHBOARD_WIDGET" values("METRIC2"."DASHBOARD_WIDGET_ID".NEXTVAL,"METRIC2"."DASHBOARD_ID".CURRVAL,24,'DB Memory Overview',2,1,2,4,0);
insert into "METRIC2"."M2_DASHBOARD_WIDGET_PARAMS" values("METRIC2"."DASHBOARD_WIDGET_PARAM_ID".NEXTVAL,"METRIC2"."DASHBOARD_WIDGET_ID".CURRVAL,93,'SELECT * FROM METRIC2.M2_WIDGET_DBMEM',24,CURRENT_TIMESTAMP);
insert into "METRIC2"."M2_DASHBOARD_WIDGET_PARAMS" values("METRIC2"."DASHBOARD_WIDGET_PARAM_ID".NEXTVAL,"METRIC2"."DASHBOARD_WIDGET_ID".CURRVAL,91,'localserver',24,CURRENT_TIMESTAMP);


insert into "METRIC2"."M2_DASHBOARD_WIDGET" values("METRIC2"."DASHBOARD_WIDGET_ID".NEXTVAL,"METRIC2"."DASHBOARD_ID".CURRVAL,25,'Physical memory Overview',2,1,2,1,0);
insert into "METRIC2"."M2_DASHBOARD_WIDGET_PARAMS" values("METRIC2"."DASHBOARD_WIDGET_PARAM_ID".NEXTVAL,"METRIC2"."DASHBOARD_WIDGET_ID".CURRVAL,94,'localserver',25,CURRENT_TIMESTAMP);
insert into "METRIC2"."M2_DASHBOARD_WIDGET_PARAMS" values("METRIC2"."DASHBOARD_WIDGET_PARAM_ID".NEXTVAL,"METRIC2"."DASHBOARD_WIDGET_ID".CURRVAL,95,'SELECT * FROM METRIC2.M2_WIDGET_RESIDENTMEM',25,CURRENT_TIMESTAMP);



insert into "METRIC2"."M2_DASHBOARD_WIDGET" values("METRIC2"."DASHBOARD_WIDGET_ID".NEXTVAL,"METRIC2"."DASHBOARD_ID".CURRVAL,28,'System Alerts',3,1,3,1,0);
insert into "METRIC2"."M2_DASHBOARD_WIDGET_PARAMS" values("METRIC2"."DASHBOARD_WIDGET_PARAM_ID".NEXTVAL,"METRIC2"."DASHBOARD_WIDGET_ID".CURRVAL,104,'SELECT * FROM METRIC2.M2_WIDGET_SYSALERTS',28,CURRENT_TIMESTAMP);
insert into "METRIC2"."M2_DASHBOARD_WIDGET_PARAMS" values("METRIC2"."DASHBOARD_WIDGET_PARAM_ID".NEXTVAL,"METRIC2"."DASHBOARD_WIDGET_ID".CURRVAL,103,'localserver',28,CURRENT_TIMESTAMP);



insert into "METRIC2"."M2_DASHBOARD_WIDGET" values("METRIC2"."DASHBOARD_WIDGET_ID".NEXTVAL,"METRIC2"."DASHBOARD_ID".CURRVAL,35,'Table Sizes',2,1,3,4,0);
insert into "METRIC2"."M2_DASHBOARD_WIDGET_PARAMS" values("METRIC2"."DASHBOARD_WIDGET_PARAM_ID".NEXTVAL,"METRIC2"."DASHBOARD_WIDGET_ID".CURRVAL,132,'localserver',35,CURRENT_TIMESTAMP);
insert into "METRIC2"."M2_DASHBOARD_WIDGET_PARAMS" values("METRIC2"."DASHBOARD_WIDGET_PARAM_ID".NEXTVAL,"METRIC2"."DASHBOARD_WIDGET_ID".CURRVAL,134,'SELECT * FROM METRIC2.M2_WIDGET_ROWCOLSIZES',35,CURRENT_TIMESTAMP);

