--Create Overview Dashboard
insert into "METRIC2"."M2_DASHBOARD" values("METRIC2"."DASHBOARD_ID".NEXTVAL,'Overview',null,null,1,null,null,null,null,null);

-- Create Widgets on Overview Dashboard
insert into "METRIC2"."M2_DASHBOARD_WIDGET" values("METRIC2"."DASHBOARD_WIDGET_ID".NEXTVAL,"METRIC2"."DASHBOARD_ID".CURRVAL,4,'All Service Started',1,1,1,1,0);
insert into "METRIC2"."M2_DASHBOARD_WIDGET_PARAMS" values("METRIC2"."DASHBOARD_WIDGET_PARAM_ID".NEXTVAL,"METRIC2"."DASHBOARD_WIDGET_ID".CURRVAL,7,'SELECT VALUE FROM METRIC2.M2_WIDGET_ALLSTARTED_VALUE',4,CURRENT_TIMESTAMP);
insert into "METRIC2"."M2_DASHBOARD_WIDGET_PARAMS" values("METRIC2"."DASHBOARD_WIDGET_PARAM_ID".NEXTVAL,"METRIC2"."DASHBOARD_WIDGET_ID".CURRVAL,6,'localserver',4,CURRENT_TIMESTAMP);
insert into "METRIC2"."M2_DASHBOARD_WIDGET_PARAMS" values("METRIC2"."DASHBOARD_WIDGET_PARAM_ID".NEXTVAL,"METRIC2"."DASHBOARD_WIDGET_ID".CURRVAL,8,'SELECT STATUS FROM METRIC2.M2_WIDGET_ALLSTARTED',4,CURRENT_TIMESTAMP);

insert into "METRIC2"."M2_DASHBOARD_WIDGET" values("METRIC2"."DASHBOARD_WIDGET_ID".NEXTVAL,"METRIC2"."DASHBOARD_ID".CURRVAL,7,'Instance Details',1,1,1,2,0);
insert into "METRIC2"."M2_DASHBOARD_WIDGET_PARAMS" values("METRIC2"."DASHBOARD_WIDGET_PARAM_ID".NEXTVAL,"METRIC2"."DASHBOARD_WIDGET_ID".CURRVAL,22,'SELECT VALUE FROM METRIC2.M2_WIDGET_INSTANCEID',7,CURRENT_TIMESTAMP);
insert into "METRIC2"."M2_DASHBOARD_WIDGET_PARAMS" values("METRIC2"."DASHBOARD_WIDGET_PARAM_ID".NEXTVAL,"METRIC2"."DASHBOARD_WIDGET_ID".CURRVAL,21,'localserver',7,CURRENT_TIMESTAMP);
insert into "METRIC2"."M2_DASHBOARD_WIDGET_PARAMS" values("METRIC2"."DASHBOARD_WIDGET_PARAM_ID".NEXTVAL,"METRIC2"."DASHBOARD_WIDGET_ID".CURRVAL,23,'SELECT VALUE FROM METRIC2.M2_WIDGET_INSTANCENUMBER',7,CURRENT_TIMESTAMP);


insert into "METRIC2"."M2_DASHBOARD_WIDGET" values("METRIC2"."DASHBOARD_WIDGET_ID".NEXTVAL,"METRIC2"."DASHBOARD_ID".CURRVAL,8,'Current Connections',1,1,1,4,10);
insert into "METRIC2"."M2_DASHBOARD_WIDGET_PARAMS" values("METRIC2"."DASHBOARD_WIDGET_PARAM_ID".NEXTVAL,"METRIC2"."DASHBOARD_WIDGET_ID".CURRVAL,24,'localserver',8,CURRENT_TIMESTAMP);
insert into "METRIC2"."M2_DASHBOARD_WIDGET_PARAMS" values("METRIC2"."DASHBOARD_WIDGET_PARAM_ID".NEXTVAL,"METRIC2"."DASHBOARD_WIDGET_ID".CURRVAL,27,'SELECT CNT FROM METRIC2.M2_WIDGET_RUNNINGCONNETIONS',8,CURRENT_TIMESTAMP);
insert into "METRIC2"."M2_DASHBOARD_WIDGET_PARAMS" values("METRIC2"."DASHBOARD_WIDGET_PARAM_ID".NEXTVAL,"METRIC2"."DASHBOARD_WIDGET_ID".CURRVAL,30,'0',8,CURRENT_TIMESTAMP);
insert into "METRIC2"."M2_DASHBOARD_WIDGET_PARAMS" values("METRIC2"."DASHBOARD_WIDGET_PARAM_ID".NEXTVAL,"METRIC2"."DASHBOARD_WIDGET_ID".CURRVAL,26,'Users',8,CURRENT_TIMESTAMP);

insert into "METRIC2"."M2_DASHBOARD_WIDGET" values("METRIC2"."DASHBOARD_WIDGET_ID".NEXTVAL,"METRIC2"."DASHBOARD_ID".CURRVAL,12,'Component Overview',3,1,2,1,0);
insert into "METRIC2"."M2_DASHBOARD_WIDGET_PARAMS" values("METRIC2"."DASHBOARD_WIDGET_PARAM_ID".NEXTVAL,"METRIC2"."DASHBOARD_WIDGET_ID".CURRVAL,44,'SELECT STATUS FROM METRIC2.M2_WIDGET_SYSOVERVIEW',12,CURRENT_TIMESTAMP);
insert into "METRIC2"."M2_DASHBOARD_WIDGET_PARAMS" values("METRIC2"."DASHBOARD_WIDGET_PARAM_ID".NEXTVAL,"METRIC2"."DASHBOARD_WIDGET_ID".CURRVAL,43,'localserver',12,CURRENT_TIMESTAMP);


insert into "METRIC2"."M2_DASHBOARD_WIDGET" values("METRIC2"."DASHBOARD_WIDGET_ID".NEXTVAL,"METRIC2"."DASHBOARD_ID".CURRVAL,15,'Time (PST)',1,1,1,3,0);


insert into "METRIC2"."M2_DASHBOARD_WIDGET" values("METRIC2"."DASHBOARD_WIDGET_ID".NEXTVAL,"METRIC2"."DASHBOARD_ID".CURRVAL,21,'System Overview',4,1,3,1,0);
insert into "METRIC2"."M2_DASHBOARD_WIDGET_PARAMS" values("METRIC2"."DASHBOARD_WIDGET_PARAM_ID".NEXTVAL,"METRIC2"."DASHBOARD_WIDGET_ID".CURRVAL,75,'localserver',21,CURRENT_TIMESTAMP);
insert into "METRIC2"."M2_DASHBOARD_WIDGET_PARAMS" values("METRIC2"."DASHBOARD_WIDGET_PARAM_ID".NEXTVAL,"METRIC2"."DASHBOARD_WIDGET_ID".CURRVAL,76,'SELECT SM FROM METRIC2.M2_WIDGET_TOTAL_CPU',21,CURRENT_TIMESTAMP);
insert into "METRIC2"."M2_DASHBOARD_WIDGET_PARAMS" values("METRIC2"."DASHBOARD_WIDGET_PARAM_ID".NEXTVAL,"METRIC2"."DASHBOARD_WIDGET_ID".CURRVAL,77,'SELECT SM FROM METRIC2.M2_WIDGET_SYS_MEM',21,CURRENT_TIMESTAMP);
insert into "METRIC2"."M2_DASHBOARD_WIDGET_PARAMS" values("METRIC2"."DASHBOARD_WIDGET_PARAM_ID".NEXTVAL,"METRIC2"."DASHBOARD_WIDGET_ID".CURRVAL,80,'SELECT VALUE FROM METRIC2.M2_WIDGET_DISTRIBUTED_VALUE',21,CURRENT_TIMESTAMP);
insert into "METRIC2"."M2_DASHBOARD_WIDGET_PARAMS" values("METRIC2"."DASHBOARD_WIDGET_PARAM_ID".NEXTVAL,"METRIC2"."DASHBOARD_WIDGET_ID".CURRVAL,79,'SELECT VALUE FROM METRIC2.M2_WIDGET_ALLSTARTED_VALUE',21,CURRENT_TIMESTAMP);


insert into "METRIC2"."M2_DASHBOARD_WIDGET" values("METRIC2"."DASHBOARD_WIDGET_ID".NEXTVAL,"METRIC2"."DASHBOARD_ID".CURRVAL,35,'Tables Sizes',2,1,2,4,0);
insert into "METRIC2"."M2_DASHBOARD_WIDGET_PARAMS" values("METRIC2"."DASHBOARD_WIDGET_PARAM_ID".NEXTVAL,"METRIC2"."DASHBOARD_WIDGET_ID".CURRVAL,132,'localserver',35,CURRENT_TIMESTAMP);
insert into "METRIC2"."M2_DASHBOARD_WIDGET_PARAMS" values("METRIC2"."DASHBOARD_WIDGET_PARAM_ID".NEXTVAL,"METRIC2"."DASHBOARD_WIDGET_ID".CURRVAL,134,'SELECT * FROM METRIC2.M2_WIDGET_ROWCOLSIZES',35,CURRENT_TIMESTAMP);

insert into "METRIC2"."M2_DASHBOARD_WIDGET" values("METRIC2"."DASHBOARD_WIDGET_ID".NEXTVAL,"METRIC2"."DASHBOARD_ID".CURRVAL,17,'Las Vegas Weather',1,1,1,5,0);
insert into "METRIC2"."M2_DASHBOARD_WIDGET_PARAMS" values("METRIC2"."DASHBOARD_WIDGET_PARAM_ID".NEXTVAL,"METRIC2"."DASHBOARD_WIDGET_ID".CURRVAL,70,' 89104',17,CURRENT_TIMESTAMP);


insert into "METRIC2"."M2_DASHBOARD_WIDGET" values("METRIC2"."DASHBOARD_WIDGET_ID".NEXTVAL,"METRIC2"."DASHBOARD_ID".CURRVAL,30,'SAP Stock Price',1,1,3,5,360);
insert into "METRIC2"."M2_DASHBOARD_WIDGET_PARAMS" values("METRIC2"."DASHBOARD_WIDGET_PARAM_ID".NEXTVAL,"METRIC2"."DASHBOARD_WIDGET_ID".CURRVAL,122,'SAP',30,CURRENT_TIMESTAMP);


insert into "METRIC2"."M2_DASHBOARD_WIDGET" values("METRIC2"."DASHBOARD_WIDGET_ID".NEXTVAL,"METRIC2"."DASHBOARD_ID".CURRVAL,31,'@metricsquared',2,3,1,6,0);
insert into "METRIC2"."M2_DASHBOARD_WIDGET_PARAMS" values("METRIC2"."DASHBOARD_WIDGET_PARAM_ID".NEXTVAL,"METRIC2"."DASHBOARD_WIDGET_ID".CURRVAL,112,' @metricsquared',31,CURRENT_TIMESTAMP);
insert into "METRIC2"."M2_DASHBOARD_WIDGET_PARAMS" values("METRIC2"."DASHBOARD_WIDGET_PARAM_ID".NEXTVAL,"METRIC2"."DASHBOARD_WIDGET_ID".CURRVAL,115,'385571773112012800',31,CURRENT_TIMESTAMP);
insert into "METRIC2"."M2_DASHBOARD_WIDGET_PARAMS" values("METRIC2"."DASHBOARD_WIDGET_PARAM_ID".NEXTVAL,"METRIC2"."DASHBOARD_WIDGET_ID".CURRVAL,113,'5',31,CURRENT_TIMESTAMP);

insert into "METRIC2"."M2_DASHBOARD_WIDGET" values("METRIC2"."DASHBOARD_WIDGET_ID".NEXTVAL,"METRIC2"."DASHBOARD_ID".CURRVAL,27,'Connections',2,1,4,1,0);
insert into "METRIC2"."M2_DASHBOARD_WIDGET_PARAMS" values("METRIC2"."DASHBOARD_WIDGET_PARAM_ID".NEXTVAL,"METRIC2"."DASHBOARD_WIDGET_ID".CURRVAL,102,'SELECT STATUS FROM METRIC2.M2_WIDGET_CONNECTIONS',27,CURRENT_TIMESTAMP);


insert into "METRIC2"."M2_DASHBOARD_WIDGET" values("METRIC2"."DASHBOARD_WIDGET_ID".NEXTVAL,"METRIC2"."DASHBOARD_ID".CURRVAL,9,'CPU Usage',1,1,3,5,10);
insert into "METRIC2"."M2_DASHBOARD_WIDGET_PARAMS" values("METRIC2"."DASHBOARD_WIDGET_PARAM_ID".NEXTVAL,"METRIC2"."DASHBOARD_WIDGET_ID".CURRVAL,32,'localserver',9,CURRENT_TIMESTAMP);
insert into "METRIC2"."M2_DASHBOARD_WIDGET_PARAMS" values("METRIC2"."DASHBOARD_WIDGET_PARAM_ID".NEXTVAL,"METRIC2"."DASHBOARD_WIDGET_ID".CURRVAL,36,'line',9,CURRENT_TIMESTAMP);
insert into "METRIC2"."M2_DASHBOARD_WIDGET_PARAMS" values("METRIC2"."DASHBOARD_WIDGET_PARAM_ID".NEXTVAL,"METRIC2"."DASHBOARD_WIDGET_ID".CURRVAL,35,'20',9,CURRENT_TIMESTAMP);
insert into "METRIC2"."M2_DASHBOARD_WIDGET_PARAMS" values("METRIC2"."DASHBOARD_WIDGET_PARAM_ID".NEXTVAL,"METRIC2"."DASHBOARD_WIDGET_ID".CURRVAL,33,'SELECT CPU FROM METRIC2.M2_WIDGET_DB_CPU',9,CURRENT_TIMESTAMP);

--Insert a sample history for CPU
-- DWP ID, min value, max value, start hour, end hour, add_days
CALL METRIC2.M2_P_HISTGENERATOR("METRIC2"."DASHBOARD_WIDGET_PARAM_ID".CURRVAL, 1, 20, 1, 19, -1);
CALL METRIC2.M2_P_HISTGENERATOR("METRIC2"."DASHBOARD_WIDGET_PARAM_ID".CURRVAL, 80, 90, 20, 22, -1);
CALL METRIC2.M2_P_HISTGENERATOR("METRIC2"."DASHBOARD_WIDGET_PARAM_ID".CURRVAL, 1, 20, 23, 23, -1);


insert into "METRIC2"."M2_ALERT" values("METRIC2"."ALERT_ID".NEXTVAL, "METRIC2"."DASHBOARD_WIDGET_ID".CURRVAL,'value','>',80,'',1,0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);






