-- Ensure script server is enabled, running: daemon.ini> script server instances = 1
-- The Install Script.sql from metric2 creates all the tables needed in the m2 schema. The script below creates the necessary functions in _SYS_AFL schema.

SETSCHEMA _SYS_AFL;

DROPTYPE PAL_T_TS_DATA;
DROPTYPE PAL_T_TS_PARAMS;
DROPTYPE PAL_T_TS_RESULTS;

DROPTABLE PAL_TS_SIGNATURE;

CREATETYPE PAL_T_TS_DATA ASTABLE (ID INT, VALUEDOUBLE);
CREATETYPE PAL_T_TS_PARAMS ASTABLE (NAME VARCHAR(60), INTARGS INTEGER, DOUBLEARGS DOUBLE, STRINGARGS VARCHAR (100));
CREATETYPE PAL_T_TS_RESULTS ASTABLE (ID INT, VALUEDOUBLE);

CREATECOLUMNTABLE PAL_TS_SIGNATURE (ID INTEGER, TYPENAME VARCHAR(100), DIRECTION VARCHAR(100));
INSERTINTO PAL_TS_SIGNATURE VALUES (1, '_SYS_AFL.PAL_T_TS_DATA', 'in' );
INSERTINTO PAL_TS_SIGNATURE VALUES (2, '_SYS_AFL.PAL_T_TS_PARAMS', 'in' );
INSERTINTO PAL_TS_SIGNATURE VALUES (3, '_SYS_AFL.PAL_T_TS_RESULTS', 'out' );

CALLSYSTEM.AFL_WRAPPER_ERASER ('PAL_TS_S');

CALLSYSTEM.AFL_WRAPPER_GENERATOR ('PAL_TS_S', 'AFLPAL', 'SINGLESMOOTH', _SYS_AFL.PAL_TS_SIGNATURE);
