CREATE SCHEMA "STORE";

UPDATE "_SYS_XS" ."SQL_CONNECTIONS" SET username = 'METRIC2USER' WHERE name = 'lilabs::storeuser';

GRANT SELECT ON SCHEMA STORE TO METRIC2ROLE;
GRANT INSERT ON SCHEMA STORE TO METRIC2ROLE;
GRANT DELETE ON SCHEMA STORE TO METRIC2ROLE;
GRANT DROP ON SCHEMA STORE TO METRIC2ROLE;
GRANT EXECUTE ON SCHEMA STORE TO METRIC2ROLE;

CREATE ROW TABLE "STORE"."M2_PILL"  ( "CHOICE" TINYINT CS_INT, "ADDED" LONGDATE CS_LONGDATE DEFAULT CURRENT_TIMESTAMP, "CLIENTIP" VARCHAR(20) CS_STRING ) ;

CREATE VIEW "STORE"."CUSTOM_BLUE_PILL" ( "CNT" ) AS SELECT
	 COUNT(CHOICE) AS CNT 
FROM STORE.M2_PILL 
WHERE CHOICE = 0 WITH READ ONLY;

CREATE VIEW "STORE"."CUSTOM_RED_PILL" ( "CNT" ) AS SELECT
	 COUNT(CHOICE) AS CNT 
FROM STORE.M2_PILL 
WHERE CHOICE = 1 WITH READ ONLY;


CREATE VIEW "STORE"."SALES_BY_BUYER" ( "CLIENT", "CNT" ) AS 
SELECT
CLIENTIP,
	 COUNT(CHOICE) AS CNT 
FROM STORE.M2_PILL 
GROUP BY CLIENTIP 
ORDER BY CNT DESC WITH READ ONLY;

CREATE VIEW "STORE"."SALES_BY_TYPE" ( "CHOICE", "CNT" ) AS 
SELECT
	 CHOICE,
	 COUNT(CHOICE) AS CNT 
FROM STORE.M2_PILL 
GROUP BY CHOICE
ORDER BY CHOICE WITH READ ONLY

