-- Schema + User
CREATE SCHEMA "METRIC2";
CREATE USER METRIC2USER PASSWORD ChangeMe123; --Issue with user needing to authenticate manually to reset t he password
CREATE ROLE METRIC2ROLE;
GRANT SELECT ON SCHEMA METRIC2 TO METRIC2ROLE;
GRANT SELECT ON SCHEMA SYS TO METRIC2ROLE;
GRANT SELECT ON SCHEMA _SYS_STATISTICS TO METRIC2ROLE;
GRANT SELECT ON SCHEMA PUBLIC TO METRIC2ROLE;
GRANT INSERT ON SCHEMA METRIC2 TO METRIC2ROLE;
GRANT DELETE ON SCHEMA METRIC2 TO METRIC2ROLE;
GRANT AFL__SYS_AFL_AFLPAL_EXECUTE TO METRIC2ROLE;
GRANT DROP ON SCHEMA METRIC2 TO METRIC2ROLE;
GRANT EXECUTE ON SCHEMA METRIC2 TO METRIC2ROLE;
GRANT METRIC2ROLE TO METRIC2USER WITH ADMIN OPTION;